### ISSUE TITLE
CarThing error when doing restore_device

### ISSUE THREAD

**Issue by hayanboi** [BluDood/GlanceThing#12] opened 2024-11-05 08:51 UTC
I got my CarThing in burn mode, after that I went to step 4 and run the command:

python superbird_tool.py --restore_device C:\Users\hayan\Downloads\CarThingTutorial\Dumps

C:\Users\hayan\Downloads\CarThingTutorial\Dumps is the path for the extracted files, but I get an output saying this:

C:\Users\hayan\Downloads\CarThingTutorial\superbird-tool-main>py ./superbird_tool.py --restore_device C:\Users\hayan\Downloads\CarThingTutorial\Dumps
Spotify Car Thing (superbird) toolkit, v0.1.0, by bishopdynamics
     https://github.com/bishopdynamics/superbird-tool

Found device booted in USB Burn Mode (ready for commands)
restoring entire device from dumpfiles in C:\Users\hayan\Downloads\CarThingTutorial\Dumps
Error: missing expected dump file: C:\Users\hayan\Downloads\CarThingTutorial\Dumps/settings.ext4

I am using Windows 11 and Python 3.10.11. I installed the latest dump in the MEGA folder and I am not too sure on what is happening. I can say I do not see a settings.ext4 nor a data.ext4 but the ReadMe.txt states, "The settings and data partitions aren't required. If they're missing, they will be formatted." What am I doing wrong?

**Comment by BluDood** [comment] 2024-11-05 09:02
Hi! You are supposed to download a single image file, not the entire folder. I also see that the MEGA folder changed structure, so I have updated the link in the wiki. [Here](https://mega.nz/folder/NxNXQCaT#-n1zkoXsJuw-5rQ-ZYzRJw/file/ItViTbLT) is a current direct link to download the image :)

**Comment by Doaky** [comment] 2024-11-06 03:42
Hey! I was having this issue earlier today and it ended up being due to using an outdated version of superbird. Using superbird toolkit, v0.1.7, [here](https://github.com/thinglabsoss/superbird-tool/)should work

**Comment by williamtcastro** [comment] 2024-11-06 21:51
We from Thing Labs recommend downloading from [thingify.tools](https://thingify.tools/firmware/P3QZbZIDWnp5m_azQFQqP?tab=info)

**Comment by BluDood** [comment] 2024-11-06 22:04
> We from Thing Labs recommend downloading from [thingify.tools](https://thingify.tools/firmware/P3QZbZIDWnp5m_azQFQqP?tab=info)

@williamtcastro What's the difference between the ThingLabs image and the other ADB images, for example `8.4.4_adb_enabled-new.tar.xz`? Maybe I'll link to them in my wiki instead :)

**Comment by williamtcastro** [comment] 2024-11-06 22:06
The 8.9.2 is based on the last Spotify based image and some improvements such as RDNIS and stability improvements for adb

**Comment by BluDood** [comment] 2024-11-08 18:45
> The 8.9.2 is based on the last Spotify based image and some improvements such as RDNIS and stability improvements for adb, also the 8.9.2 works more stable on macOS the old 8.4.4-new that seems flaky regarding adb

Updated [the flashing guide](https://github.com/BluDood/GlanceThing/wiki/Flashing-the-CarThing) to include the Thing Labs image, I confirmed that it worked just fine :)

On that note, I'll close this issue since the problem has been identified, you need to extract the image to a folder before trying to flash it. Double-check that you've done [this step](https://github.com/BluDood/GlanceThing/wiki/Flashing-the-CarThing#downloading-the-correct-image-and-extracting-it) ;)

**Closed by BluDood** 2024-11-08 18:45 UTC
Labels: question
